In [ ]:
import numpy as np           #Импортирована библиотека numpy
zero=np.zeros(10)            #Массив из 10 нулей
print(zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
one=np.ones(10)              #массив из 10 едениц
print(one)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
five=np.ones(10)*5     #Массив из 10 пятерок
print(five)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
num=np.arange(10,51)         #Массив из целых чисел от 10 до 50. Включая 50.
print(num)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
num2=np.arange(10,51,2)     #Массив из целых четных чисел от 10 до 50. Включая 50
print(num2)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
num3=np.arange(0,9)        #Матрица 3х3 с числами от 0 до 8
matrx=np.array(num3)
print(matrx.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
onematrx=np.ones(9)           #Еденичная матрица 3х3
print(onematrx.reshape(3,3))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
numbran=np.random.rand()       #Случайное число от 0 до 1
print(numbran)

0.8344135138024256


In [ ]:
numbran2=np.random.randn(25)      #Массив из 25 случайных чисел, взятых из стандартного нормального распределения
print(numbran2)

24.306837443834436


In [ ]:
a=np.linspace(0.01,1,100)      #Создать матрицу исползуя numpy
print(a.reshape(10,10))

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
mat = np.arange(1,26).reshape(5,5)     
#print(mat)
arr=mat[2:, 1:]
print(arr)                           #Вернуть матрицу из стартовой

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
mat = np.arange(1,26).reshape(5,5)     #Вернуть значение 20
#print(mat)
print(mat[3][4])

20


In [ ]:
mat = np.arange(1,26).reshape(5,5)     
#print(mat)
print(mat[0:3,1].reshape(3,1))

[[ 2]
 [ 7]
 [12]]


In [ ]:
mat = np.arange(1,26).reshape(5,5)     
#print(mat)
print(mat[4:])

[[21 22 23 24 25]]


In [ ]:
mat = np.arange(1,26).reshape(5,5)     
#print(mat)
print(mat[3:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
mat = np.arange(1,26).reshape(5,5)     #сумма всех элементов в матрице
#print(mat)
print(mat.sum())

325


In [ ]:
mat = np.arange(1,26).reshape(5,5)     #стаднадртное отклонение
#print(mat)
print(mat.std())

7.211102550927978


In [ ]:
mat = np.arange(1,26).reshape(5,5)     
print(mat)         #Сумма значений в каждой колонке
print('_________________')
print(mat.sum(axis=0))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
_________________
[55 60 65 70 75]
